config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resource :home, only: [:index]

  devise_for :candidates, controllers: {
    sessions: 'candidates/sessions',
    passwords: 'candidates/passwords',
    registrations: 'candidates/registrations'
  }
  devise_for :corporations, controllers: {
    sessions: 'corporations/sessions',
    passwords: 'corporations/passwords',
    registrations: 'corporations/registrations'
  }
  
  resources :jobs
  resources :candidates, only: [:index, :show]
  resources :chats, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :coporation
  has_many :entries, dependent: :destroy
  
  validates :title, presence: true
  validates :status, presence: true
  validates :MonthlyOrAnnual, presence: true
  validates :salary, presence: true
  validates :benefitProgram, presence: true
  validates :holiday, presence: true
  validates :description, presence: true

  enum status: {
    正社員:0,契約社員:1,業務委託:2,インターン:3,パート・アルバイト:4
  }
  
  enum workplace: {
    リモート勤務可:0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }
  
  enum MonthlyOrAnnual: {
    月収:0,年収:1
  }
  
  enum language: {
    Javascript:0, Ruby:1, PHP:2, Python:3, Java:4,
    C:5, Cプラスプラス:6, Cシャープ:7, Go:8, Scala:9, 
    Dart:10, Kotlin:11, Swift:12, R:13, Julia:14, COBOL:15, Perl:16, ObjectiveC:17,
    TypeScript:18, HTML・CSS:19, Firebase:20, SQL:21, GAS:22, その他:23
  }
  
  enum framework: {
    AngularJS:1, Vuejs:2, jQuery:3, Reactjs:4, Riotjs:5, Hyperapp:6,
    RubyonRails:7, Sinatra:8, cubamicroframework:9, Ramaze:10, HANAMI:11, Padrino:12,
    Laravel:13, CakePHP:14, Symfony:15, CodeIgniter:16, ZendFramework:17, Phalcon:18, Slim:19, Yii:20, FuelPHP:21, Flight:22,
    Django:23, Flask:24, Bottle:25, Tornado:26, web2Py:27,
    Struts:28, SparkFramework:29, JavaServerFaces:30, PlayFramework:31, Spring:32,
    TreeFrogFramework:33, Qt:34, Oatプラスプラス:35, crow:36, Unity:37, Cocos2dx:38,
    echo:39, gin:40, aero:41, ORM:42, gorm:43, pop:44, sqlx:45, slacker:46, aurora:47,
    PlayFramework:48, Finatra:49, SkinnyFramework:50, Lift:51, Xitrum:52, Scalatra:53,
    Flutter:54,
    Ktor:55, kara:56, SpringBoot:57, Jooby:58, javalin:59,
    perfect:60, Swifton:61, Slimane:62, Kitura:63, Express:64, Vapor:65, HTTPSwiftServer:66, ReactNative:67,
    Genie:68,
    Mojolicios:69, Dancer:70, Catalyst:71, Amon2:72, TripletaiL:73, Ark:74,
    NestJS:75, Marblejs:76,
    Sass:77, BootStrap:78, Foundation:79, UIKit:80, Bulma:81, SemanticUI:82, TailWindCSS:83, MaterializeCSS:84, newcss:85, MVPcss:86, Skelton:87, Milligram:88, Base:89, Minicss:90, PureCSS:91
  }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_corporation!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    if candidate_signed_in?
      @jobs = Job.all
    elsif corporation_signed_in?
      @jobs = Job.user_id == current_user.id
    else
      @jobs = Job.all
    end
  end
  
  def show
    @job = Job.find_by(id: params[:id])
  end
  
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
      flash[:notice] = "投稿されました"
    else
      redirect_to jobs_path
      flash[:alert] = "投稿に失敗しました"
    end  
  end
  
  def edit
    @job = Job.find_by(id: params[:id])
  end
  
  def update
    @job = Job.find_by(id: params[:id])
    if @job.corporation_id = current_corporation.id
      if @job.update(job_params)
        redirect_to jobs_path
        flash[:notice] = "更新を保存しました"
      else
        flash[:alert] = "更新に失敗しました"
        render :edit
      end
    end  
  end
  
  def destroy
    @job = Job.find_by(id: params[:id])  
    if @job.corporation_id = current_corporation.id
      flash[:notice] = "投稿が削除されました"
    else
      flash[:alert] = "削除に失敗しました"
    end
    redirect_to jobs_path
  end
  
  private
    def job_params
      params.require(:job).permit(:title, :status, :monthlyOrAnnual, :salary, :benefitProgram, :holiday,  :language, :framework, :characteristics, :skillset, :selectionProcess, :training, :startingDate, :workplace, :access, :description).merge(corporation_id: current_user.id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div class="ui centered grid">
<%= link_to "新規投稿", new_job_path, class:"ui blue button" %>
  <div></div>
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
  <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  
    <div class="ui card">
    <div class="content">
      <div class="header">Cute Dog</div>
      <div class="meta">2 days ago</div>
      <div class="description">
        <p>Cute dogs come in a variety of shapes and sizes. Some cute dogs are cute for their adorable faces, others for their tiny stature, and even others for their massive size.</p>
        <p>Many people also have their own barometers for what makes a cute dog.</p>
      </div>
    </div>
    <div class="extra content">
      <i class="check icon"></i>
      121 Votes
    </div>
  </div>
  

  
  
  <div></div>
</div>

<div class="ui card">
  <div class="content">
    <div class="header">〇〇とのチャット</div>
  </div>
  <div class="content">
    <h4 class="ui sub header">Activity</h4>
    <div class="ui small feed">
      <div class="event">
        <div class="content">
          <div class="summary">
             <a>Elliot Fu</a> added <a>Jenny Hess</a> to the project
          </div>
        </div>
      </div>
      <div class="event">
        <div class="content">
          <div class="summary">
             <a>Stevie Feliciano</a> was added as an <a>Administrator</a>
          </div>
        </div>
      </div>
      <div class="event">
        <div class="content">
          <div class="summary">
             <a>Helen Troy</a> added two pictures
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="extra content">
     <form class="ui reply form">
    <div class="field">
      <textarea></textarea>
    </div>
    <div class="ui blue labeled submit icon button">
      <i class="icon edit"></i> Add Reply
    </div>
  </form>
</div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="ui fluid icon input">
  <input type="text" placeholder="Search a very wide input...">
</div>

<div class="ui fluid action input">
  <input type="text" placeholder="Search...">
</div>

<div class="ui fluid icon input">
  <input type="text" placeholder="Search a very wide input...">
</div>

<div class="ui fluid action input">
  <input type="text" placeholder="Search...">
</div>

<div class="ui fluid icon input">
  <input type="text" placeholder="Search a very wide input...">
</div>

<div class="ui fluid action input">
  <input type="text" placeholder="Search...">
</div>

app/views/jobs/show.html.erb
<% if candidate_signed_in? %>
  <button>応募</button>
<% else %>
  <p>if @Job.user_id == current_user.id</p>
    <button>編集</button>
    <button>削除</button>
  <p>else ボタンなし</p>
<% end %>

<h4 class="ui horizontal divider header">
  <i class="tag icon"></i>
  Description
</h4>
<p>Doggie treats are good for all times of the year. Proven to be eaten by 99.9% of all dogs worldwide.</p>
<h4 class="ui horizontal divider header">
  <i class="bar chart icon"></i>
  Specifications
</h4>
<table class="ui definition table">
  <tbody>
    <tr>
      <td class="two wide column">Size</td>
      <td>1" x 2"</td>
    </tr>
    <tr>
      <td>Weight</td>
      <td>6 ounces</td>
    </tr>
    <tr>
      <td>Color</td>
      <td>Yellowish</td>
    </tr>
    <tr>
      <td>Odor</td>
      <td>Not Much Usually</td>
    </tr>
  </tbody>
</table>